### ISSUE TITLE
useOmeka_View_Helper_FileMarkup in a plugin

### ISSUE THREAD

**Issue by bpalme** [jmague/TeiDisplay#1]
This isn't really an issue so I apologize, but I couldn't help but laugh at your "under" documentation.  I guess there is a fine line between un-documented and under-documented.  anyway, I was trying to figure out how to useOmeka_View_Helper_FileMarkup in a plugin and this was just what I needed.  thanks for being there.

**Comment by jmague** [comment]
Given Maybe under-un-documented

**Comment by jmague** [comment]
You're right, undocumented is probably more accurate in this case. Glad it had helped anyway
